package XML2MPS.Importer;

/*Generated by MPS */

import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import java.io.File;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class XMLImporter {


  public static void importXMLDocument(String path) {
    DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
    try {
      DocumentBuilder builder = factory.newDocumentBuilder();
      File f = new File(path);
      Document doc = builder.parse(f);
      Element root = doc.getDocumentElement();
      System.out.println(root.getChildNodes());
    } catch (Exception e) {
    }
  }

}
