package NewLanguage10.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Ids = 0;
  public static final int Machines = 1;
  public static final int States = 2;
  public static final int Trans = 3;
  public static final int id = 4;
  public static final int machine = 5;
  public static final int state = 6;
  public static final int transition = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x57cddcc0dbee4083L, 0x8b4b40518c5b3739L);
    builder.put(0x3d163d232ca8d50fL, Ids);
    builder.put(0x3d163d232ca8d51dL, Machines);
    builder.put(0x3d163d232ca8d521L, States);
    builder.put(0x3d163d232ca8d518L, Trans);
    builder.put(0x3d163d232ca8d512L, id);
    builder.put(0x3d163d232ca8d51eL, machine);
    builder.put(0x3d163d232ca8d522L, state);
    builder.put(0x3d163d232ca8d519L, transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
