package NewLanguag3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Ids = 0;
  public static final int Machines = 1;
  public static final int States = 2;
  public static final int Trans = 3;
  public static final int id = 4;
  public static final int machine = 5;
  public static final int state = 6;
  public static final int transition = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x6ca33e3e67d54f63L, 0x9d311a611e3ebd7fL);
    builder.put(0x59b7f9c6ffbf6616L, Ids);
    builder.put(0x59b7f9c6ffbf6620L, Machines);
    builder.put(0x59b7f9c6ffbf666fL, States);
    builder.put(0x59b7f9c6ffbf661bL, Trans);
    builder.put(0x59b7f9c6ffbf6619L, id);
    builder.put(0x59b7f9c6ffbf6621L, machine);
    builder.put(0x59b7f9c6ffbf6670L, state);
    builder.put(0x59b7f9c6ffbf661cL, transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
