package pluginBuildSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import jetbrains.mps.ide.actions.Tools_ActionGroup;

public class PluginBuildSolution_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("pluginBuildSolution");
  public PluginBuildSolution_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new TestAction_Action());
    // groups 
    addGroup(new TestPluginActionGroup_ActionGroup());
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(TestPluginActionGroup_ActionGroup.ID, Tools_ActionGroup.ID, Tools_ActionGroup.LABEL_ID_customTools);
  }
}
