package pluginBuildSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class TestPluginActionGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "pluginBuildSolution.plugin.TestPluginActionGroup_ActionGroup";
  public TestPluginActionGroup_ActionGroup() {
    super("TestPluginActionGroup", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    TestPluginActionGroup_ActionGroup.this.addAction("pluginBuildSolution.plugin.TestAction_Action");
  }
}
