package plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class ImportXMLActionGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "plugin.plugin.ImportXMLActionGroup_ActionGroup";
  public ImportXMLActionGroup_ActionGroup() {
    super("ImportXMLActionGroup", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    ImportXMLActionGroup_ActionGroup.this.addAction("plugin.plugin.importXMLAction_Action");
  }
}
