package plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import jetbrains.mps.ide.actions.Tools_ActionGroup;

public class Plugin_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("plugin");
  public Plugin_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new importXMLAction_Action());
    // groups 
    addGroup(new ImportXMLActionGroup_ActionGroup());
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(ImportXMLActionGroup_ActionGroup.ID, Tools_ActionGroup.ID, Tools_ActionGroup.LABEL_ID_customTools);
  }
}
