package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAstNode = createDescriptorForAstNode();
  /*package*/ final ConceptDescriptor myConceptNonTerminalNode = createDescriptorForNonTerminalNode();
  /*package*/ final ConceptDescriptor myConceptRascalImporter = createDescriptorForRascalImporter();
  /*package*/ final ConceptDescriptor myConceptTerminalNode = createDescriptorForTerminalNode();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAstNode, myConceptNonTerminalNode, myConceptRascalImporter, myConceptTerminalNode);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AstNode:
        return myConceptAstNode;
      case LanguageConceptSwitch.NonTerminalNode:
        return myConceptNonTerminalNode;
      case LanguageConceptSwitch.RascalImporter:
        return myConceptRascalImporter;
      case LanguageConceptSwitch.TerminalNode:
        return myConceptTerminalNode;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAstNode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "AstNode", 0x7694383cc1724f9bL, 0xba3e2e4103639d0dL, 0xef7205cf8eef2d4L);
    b.class_(false, true, false);
    b.origin("r:c1b74b72-975a-42f3-b7fb-5fbd742cc995(NewLanguage.structure)/1078366219464012500");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNonTerminalNode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "NonTerminalNode", 0x7694383cc1724f9bL, 0xba3e2e4103639d0dL, 0xef7205cf8eef15eL);
    b.class_(false, false, false);
    b.super_("NewLanguage.structure.AstNode", 0x7694383cc1724f9bL, 0xba3e2e4103639d0dL, 0xef7205cf8eef2d4L);
    b.origin("r:c1b74b72-975a-42f3-b7fb-5fbd742cc995(NewLanguage.structure)/1078366219464012126");
    b.version(2);
    b.prop("ruleName", 0xef7205cf8eef15fL, "1078366219464012127");
    b.aggregate("children", 0xef7205cf8eef164L).target(0x7694383cc1724f9bL, 0xba3e2e4103639d0dL, 0xef7205cf8eef2d4L).optional(true).ordered(true).multiple(true).origin("1078366219464012132").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRascalImporter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "RascalImporter", 0x7694383cc1724f9bL, 0xba3e2e4103639d0dL, 0xef7205cf8eef116L);
    b.class_(false, false, true);
    b.origin("r:c1b74b72-975a-42f3-b7fb-5fbd742cc995(NewLanguage.structure)/1078366219464012054");
    b.version(2);
    b.prop("path", 0xef7205cf8eef117L, "1078366219464012055");
    b.aggregate("root", 0xef7205cf8eef11cL).target(0x7694383cc1724f9bL, 0xba3e2e4103639d0dL, 0xef7205cf8eef2d4L).optional(false).ordered(true).multiple(false).origin("1078366219464012060").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTerminalNode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "TerminalNode", 0x7694383cc1724f9bL, 0xba3e2e4103639d0dL, 0xef7205cf8eef121L);
    b.class_(false, false, false);
    b.super_("NewLanguage.structure.AstNode", 0x7694383cc1724f9bL, 0xba3e2e4103639d0dL, 0xef7205cf8eef2d4L);
    b.origin("r:c1b74b72-975a-42f3-b7fb-5fbd742cc995(NewLanguage.structure)/1078366219464012065");
    b.version(2);
    b.prop("text", 0xef7205cf8eef154L, "1078366219464012116");
    b.aggregate("children", 0xef7205cf8eef159L).target(0x7694383cc1724f9bL, 0xba3e2e4103639d0dL, 0xef7205cf8eef121L).optional(true).ordered(true).multiple(true).origin("1078366219464012121").done();
    return b.create();
  }
}
